FROM node:11.13-alpine

WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn
COPY . ./

ENV NODE_PATH=/node_modules
ENV PATH=$PATH:/node_modules/.bin

COPY ./entrypoint.sh /tmp

RUN ["chmod", "+x", "/tmp/entrypoint.sh"]


